version: "3.7"

services:
  # El frontend no funciona en modo de desarrollo
  frontend:
    build:
      context: ./services/frontend/
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0"]

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    command: ["sh", "init-server.sh", "start"]

  chat:
    build:
      context: ./services/chat
      dockerfile: Dockerfile.prod
    command: ["uvicorn", "app:app", "--port", "8030", "--host", "0.0.0.0"]

  indexes:
    build:
      context: ./services/indexes
      dockerfile: Dockerfile.prod
    command: ["yarn", "dev"]

  reverse-proxy:
    environment:
      SITE_ADDRESS: front-e2-arqui.tk
