version: "3.7"

services:
  frontend:
    depends_on:
      - auth
    build:
      context: ./services/frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
