version: "3.7"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

services:
  postgres:
    image: postgis/postgis:14-master
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-u", "user"]
      interval: 10s
      timeout: 5s

  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s

  backend:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      INDEX_HOST: http://indexes:8080
      PORT: 8000
      DB_HOST: postgres
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: main
      DATABASE_URL: postgres://user:password@postgres:5432/main
    healthcheck:
      test: ["CMD", "curl", "-s", "http://backend:8000"]
      interval: 15s
      start_period: 15s

  frontend:
    environment:
      PORT: 3000

  reverse-proxy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  chat:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH0_DOMAIN: dev-7c2520d3.us.auth0.com
      AUTH0_API_AUDIENCE: https://PingTocAuth.com
      AUTH0_ISSUER: https://dev-7c2520d3.us.auth0.com/
      DATABASE_URL: postgresql://user:password@postgres:5432/chat
    healthcheck:
      test: ["CMD", "curl", "-s", "http://chat:8000"]
      interval: 60s
      timeout: 5s
      retries: 5

  indexes:
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: main
      REDIS_URL: redis:redis:6379
      DATABASE_URL: postgres://user:password@postgres:5432/main
