version: "3.7"

services:
  frontend:
    depends_on:
      - auth
    build:
      context: ./services/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
       - ./services/frontend/src:/workspace/src
       - /workspace/node_modules
       - /workspace/.next
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
