version: "3.7"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./services/indexes/src:/workspace/src
      - /workspace/node_modules
    command: ["sh", "init-server.sh"]

  frontend:
    build:
      context: ./services/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
       - ./services/frontend/src:/workspace/src
       - /workspace/node_modules
       - /workspace/.next
    command: ["npm", "run", "dev"]

  indexes:
    build:
      context: ./services/indexes
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/indexes/src:/workspace/src
      - /workspace/node_modules
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    command: ["sh", "init-server.sh"]

  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      redis:
        condition: service_healthy
