FROM node:16-alpine
WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm ci

COPY . .                                                                                            

EXPOSE 3000

