import React, { useState } from 'react'

import Head from 'next/head'

import Navbar from '~/components/Navbar'
import Footer from '~/components/Footer'
import UserInfo from '~/components/UserInfo'

import { getApi } from '~/lib/api'
import useLocalStorage from '~/hooks/useLocalStorage'

function UsersPage() {
  const [loading, setLoading] = useState(true);
  const [usersData, setUsersData] = useState(null);
  const [page, setPage] = useState(1);
  const [user] = useLocalStorage<User>("user");

  if (user === undefined) {
    return (
      <div />
    )
  }

  if (loading) {
    getApi(user.token, 'api/users', { 'page': page })
      .then(data => {
        setUsersData(JSON.parse(data));
        setLoading(false);
      });

    return (
      <h2>Cargando</h2>
    )
  }

  const prevPage = () => {
    setPage(page - 1);
    setLoading(true);
  }
  const nextPage = () => {
    setPage(page + 1);
    setLoading(true);
  }

  const Users = usersData.map((userS) => {
    return (
      <UserInfo user={userS} key={userS.id} />
    )
  });

  return (
    <div>
      <Head>
        <title>PingToc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar logged={user.token !== null} />
      
      <div className="flex flex-col justify-center items-center mt-10">
        <h2 className="font-semibold text-xl">Lista de usuarios</h2>
        <p>Página {page}</p>
      </div>

      <div className="grid grid-cols-3 gap-10 w-4/6 ml-auto mr-auto my-10">
        {usersData.length !== 0 ? Users : <h2> No hay más usuarios</h2>}
      </div>

      {usersData.length !== 0 ?
        <div className="flex gap-10 justify-center mb-10">
          <button 
            className="bg-sky-600 hover:bg-sky-700 p-3 rounded-md text-slate-100 text-base"
            onClick={prevPage} 
            disabled={page == 1}
          >
            {'< Página anterior'}
          </button>

          <button 
            className="bg-sky-600 hover:bg-sky-700 p-3 rounded-md text-slate-100 text-base"
            onClick={nextPage} 
            disabled={usersData.length == 0}
          >
            {'Página siguiente >'}
          </button>
        </div>
        : null}

      <Footer />
    </div>
  )
}

export default UsersPage
