import React, { useState } from 'react';
import { useUser } from '@auth0/nextjs-auth0';

import Head from 'next/head'
import styles from '../../styles/Home.module.css'

import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'

import { getApi } from '../../lib/api';

function UsersPage() {
  const { user } = useUser();  

  const [loading, setLoading] = useState(true);
  const [usersData, setUsersData] = useState(null);

  if (loading) {
    getApi('/api/users')
      .then(data => {
        setUsersData(data);
        setLoading(false);
      });
    
    return (
      <h2>Cargando</h2>
    )
  }

  console.log(usersData);

  const Users = () => {
    return (
      <div className={styles.centerContainer}>
        <h1> Lista de usuarios </h1>
        <p> Página 1 </p>
      </div>  
    )
  }
  
  return (
    <div className={styles.container}>
      <Head>
          <title>PingToc</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar logged={user !== undefined}/>
      <Users />
      <Footer />
    </div>
  )
}

export default UsersPage
