import React, { useState } from 'react'
import { useRouter } from 'next/router'
import { useUser } from '@auth0/nextjs-auth0'

import { getApi, patchApi } from '../../lib/api';

import Head from 'next/head'

import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'

import styles from '../../styles/Home.module.css'

function PingsPage() {
  const { user } = useUser();  
  const router = useRouter()

  const [loading, setLoading] = useState(true);
  const [pingsData, setPingsData] = useState(null);

  if (loading) {
    getApi('api/pings/all', null) 
      .then(data => {
        console.log(data);
        setPingsData(JSON.parse(data));
        setLoading(false);
      });

    return (
      <h2>Cargando</h2>
    )
  }

  const visitToProfile = (user) => {
    router.push({
      pathname: '/users/profile',
      query: { id: user.id },
    })
  }

  const visitFromProfile = (user) => {
    router.push({
      pathname: '/users/profile',
      query: { id: user.id },
    })
  }

  const respondingPing = (answer, id) => {
    console.log(answer);
    patchApi(`api/pings/update/${id}`, { status: answer}) 
      .then(res => {
        setLoading(true);
      });
    
  }

  const pingsToUser = pingsData.usersPingedBy.map((ping) => {
    if (ping.status == 0) {      
      return (
        <div className={styles.row}>
          <p key={ping.id}>Te han hecho un ping, <a className={styles.rowItemPress} onClick={() => visitToProfile(ping.pingedFrom)}>Visitar perfil</a></p> 
          <button className={styles.button} onClick={() => respondingPing(1, ping.id)}> 
            Aceptar
          </button> 
          <button className={styles.buttonReject} onClick={() => respondingPing(-1, ping.id)}> 
            Rechazar
          </button> 
        </div>
        
      ) 
    } else {
      return (
        <div className={styles.row}>
          <p key={ping.id}>Te han hecho un ping, <a className={styles.rowItemPress} onClick={() => visitToProfile(ping.pingedFrom)}> Visitar perfil</a> | {ping.status == 1 ? 'Aceptado' : 'Rechazado' }</p>
        </div>
      ) 
    }
    
  });

  const pingsFromUser = pingsData.pingedUsers.map((ping) => {
    return (
      <p key={ping.id}>Has hecho un ping, <a className={styles.rowItemPress} onClick={() => visitFromProfile(ping.pingedTo)}> Visitar perfil</a></p>     
    )
  });

  return (
    <div>
      <Head>
          <title>PingToc</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar logged={user !== undefined}/>
      <div>
        <h2>Pings que te han hecho:</h2>
        <div className={styles.column}>
          {pingsToUser}
        </div>
        
        <h2>Pings que has hecho:</h2>
        <div className={styles.column}>
          {pingsFromUser}
        </div>
      </div>      
      
      <Footer />
    </div>
  )
}

export default PingsPage
