name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the back and frontend branch
  push:
    branches:
      - main
      - backend
      - frontend
      - frontend-rial
  pull_request:
    branches:
      - main
      - backend
      - frontend
      - frontend-rial

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'npm'
          cache-dependency-path: ./services/frontend/package-lock.json

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true